### ISSUE TITLE
Skipped tests listed in failed tests.

### ISSUE THREAD

**Issue by cvle** [litixsoft/karma-mocha-reporter#84] opened 2016-11-20 15:06 UTC
I run the same tests for multiple browsers (using browserstack). Some tests are skipped for certain browsers. The problem is, when one browser fails a test, other browsers that skipped that test are listed in the _failed tests_ section. This prevents me from knowing which browser actually triggered the failure.

You can see below that 1 test is skipped and 1 test failed, but 2 browsers are listed in _failed tests_.

```sh
SUMMARY:
✔ 18 tests completed
ℹ 1 test skipped
✖ 1 test failed

FAILED TESTS:
  css-vendor
    .supportedValue()
      ✖ should prefix if needed
        IE 11.0.0 (Windows 8.1 0.0.0)
        Android 4.1.2 (Android 4.1.2)
```

**Comment by 4kochi** [comment] 2016-11-21 12:30
We will have a look. Are the results of the tests from browserstack public. So that we can see the other results?

**Comment by cvle** [comment] 2016-11-21 14:28
It happened while I was working on a PR locally, so the test result is not public. But there was no log indicating a problem except the summary of failed tests I posted above was not correct.

You can check out the test file here:
https://github.com/cvle/css-vendor/blob/fix-failing-tests/src/index.test.js

And the karma config:
https://github.com/cvle/css-vendor/blob/fix-failing-tests/karma.conf.js

**Comment by 4kochi** [comment] 2016-11-29 20:23
I am sorry but I am not able to reproduce the problem so far. I will close the issue for now. Feel free to open it again when there is maybe a reproducible test case.

**Closed by 4kochi** 2016-11-29 20:23 UTC

**Comment by cvle** [comment] 2016-12-01 05:44
Seems to work with the newest version. I probably had some old version installed. Sorry for wasting your time.

**Comment by cvle** [comment] 2016-12-01 05:50
This is still happening. I'll open this again, once I have a minimal repo to reproduce this.

**Comment by john-hadron** [comment] 2017-06-17 23:47
I've noticed this error when I do the following.
I run a test in multiple browsers, but skip the test in some browers. The report consistently comes out as failed.

```
describe(function() {
  before(function() {
    // Only run this suite in Firefox
    if (navigator.userAgent.indexOf("Firefox") === -1) this.skip();
  });
  
  it("always passes or skips", function() {
    expect(1).toEqual(1);
  });
});
```

```
"karma-mocha-reporter": "2.2.3"
```

```
reporters: ['junit', 'mocha', 'coverage-istanbul'],
mochaReporter: {
   showDiff: true
},
```
