### ISSUE TITLE
Highlight complex object diff

### ISSUE THREAD

**Issue by hatched** [litixsoft/karma-mocha-reporter#32] opened 2015-09-08 02:39 UTC
It would be great if the reporter would highlight the diff in a complex object instead of just dumping both the expected and actual to the console. I'm using karma-jasmine because karma-mocha doesn't show the stacktrace on error and using chai 'assert' assertions. 

Using:
- karma 0.13.9
- karma-chai-sinon 0.1.5
- karma-jasmine 0.3.6
- karma-mocha-reporter 1.1.1

**Comment by 4kochi** [comment] 2015-09-08 10:20
I guess this is a duplicate of #26 ? I am short on time right now but i will try to have a look if this can be done with the reporter.

**Comment by hatched** [comment] 2015-09-08 18:49
I spent a bit of time this morning tracing down where this information is coming from. It appears that the issue is in `jasmine-core` not emitting the proper information on an exception.

https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L1468

I'm not at all familiar with how jasmine-core operates but it appears that `karma-jasmine` _may_ be able to supply configuration values to support adding the actual and expected. At that point the data should become available to the reporter to show a pretty diff.

**Comment by 4kochi** [comment] 2015-09-09 06:43
Thanks for looking into this. I will use this as starting point.

**Comment by rosston** [comment] 2016-02-18 02:59
I've looked a bit into getting nice diffs in Karma, and it seems like the reporter is really at the mercy of the test framework/assertion library to provide the necessary data to provide the diff.

That said, karma-mocha recently added support for passing assertion errors through to the reporter (https://github.com/karma-runner/karma-mocha/pull/85). As far as I can tell, Chai is the only assertion library that would provide enough information on the errors to show a diff of expected/actual. Would it make sense to add support to this reporter for only one possible setup (i.e., karma-mocha + chai)?

**Comment by 4kochi** [comment] 2016-02-18 10:59
Hey @rosston ,

thanks for the informations. I will have a look. To get started quickly it would be nice if you could send be a `spec` file with mocha tests. Because i only use `karma-jasmine`. That would be really helpful.

**Comment by rosston** [comment] 2016-02-18 12:37
Certainly, I can put up an example spec. Would it be helpful to have a full example repo with mocha node tests too? Mocha on node seems to be the gold standard for expected/actual diffs.

**Comment by 4kochi** [comment] 2016-02-18 13:03
I guess an example spec is enough. Or is the logic the same in mocha for node.js and browser tests?

**Comment by rosston** [comment] 2016-02-18 13:19
Mocha only shows diffs when run in node. In the browser, it uses a different (HTML) reporter, which doesn't support diffs. See https://github.com/mochajs/mocha/issues/1348#issuecomment-131385808

**Comment by rosston** [comment] 2016-02-18 14:21
@4kochi Here's an example repo: https://github.com/rosston/mocha-diff-example. `test/test.js` contains the example spec. Let me know if there's anything else I can do to help.

**Closed** 2016-02-19 11:01 UTC

**Comment by 4kochi** [comment] 2016-02-19 11:50
Thanks for your help @all. Released as v1.2.0

**Comment by rosston** [comment] 2016-02-19 12:52
:joy: Yes! This has made my week. Thank you, @4kochi.
